kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false

      retention: 2d
      resources:
        requests:
          memory: 400Mi
          cpu: 200m
        limits:
          memory: 1Gi
          cpu: 500m

  grafana:
    enabled: true
    
    persistence:
      enabled: false

    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL

  alertmanager:
    enabled: false 
  kubeNodeExporter:
    enabled: true 