apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observer-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Asienka/eks-gitops-observer.git'
    targetRevision: HEAD
    path: infrastructure/charts/observer-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true